# Generated by Django 5.2.8 on 2025-11-23 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutique', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Ville/Commune')),
                ('frais_livraison', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Frais de livraison (FCFA)')),
                ('delai_livraison', models.IntegerField(verbose_name='Délai de livraison (jours)')),
                ('active', models.BooleanField(default=True, verbose_name='Zone active')),
            ],
            options={
                'verbose_name': 'Zone de livraison',
                'verbose_name_plural': 'Zones de livraison',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(max_length=20, unique=True, verbose_name='Numéro de commande')),
                ('adresse_livraison', models.TextField(verbose_name='Adresse de livraison')),
                ('montant_produits', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant produits (FCFA)')),
                ('frais_livraison', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Frais de livraison (FCFA)')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total (FCFA)')),
                ('mode_paiement', models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('MTN_MONEY', 'MTN Money'), ('MOOV_MONEY', 'Moov Money'), ('WAVE', 'Wave'), ('CARTE_BANCAIRE', 'Carte Bancaire')], max_length=20, verbose_name='Mode de paiement')),
                ('paiement_valide', models.BooleanField(default=False, verbose_name='Paiement validé')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmée'), ('EN_PREPARATION', 'En préparation'), ('EXPEDIEE', 'Expédiée'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_commande', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
                ('date_confirmation', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation')),
                ('date_expedition', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expédition")),
                ('date_livraison', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison')),
                ('notes_client', models.TextField(blank=True, null=True, verbose_name='Notes du client')),
                ('notes_admin', models.TextField(blank=True, null=True, verbose_name='Notes administrateur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('zone_livraison', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commandes.zonelivraison', verbose_name='Zone de livraison')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='CommandeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité (kg)')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (FCFA)')),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sous-total (FCFA)')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commandes.commande', verbose_name='Commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
            },
        ),
    ]
