# Generated by Django 5.2.8 on 2025-12-03 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_codepromo_pointsfidelite_historiquepoints'),
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='code_promo_utilise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.codepromo', verbose_name='Code promo utilisé'),
        ),
        migrations.AddField(
            model_name='commande',
            name='reduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant réduction (FCFA)'),
        ),
    ]
