# Generated by Django 5.2.8 on 2025-11-23 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Legume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('COURGE', 'Courge'), ('GOMBO', 'Gombo'), ('AUBERGINE', 'Aubergine')], max_length=50, unique=True, verbose_name='Type de légume')),
                ('cycle_jours', models.IntegerField(help_text='Nombre de jours entre plantation et récolte', verbose_name='Cycle de culture (jours)')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Légume',
                'verbose_name_plural': 'Légumes',
            },
        ),
        migrations.CreateModel(
            name='Plantation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_plantation', models.DateField(verbose_name='Date de plantation')),
                ('quantite_plantee', models.DecimalField(decimal_places=2, help_text='Estimation de la quantité à récolter', max_digits=10, verbose_name='Quantité plantée (kg)')),
                ('date_recolte_prevue', models.DateField(blank=True, null=True, verbose_name='Date de récolte prévue')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('RECOLTEE', 'Récoltée')], default='EN_COURS', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('legume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.legume', verbose_name='Légume')),
            ],
            options={
                'verbose_name': 'Plantation',
                'verbose_name_plural': 'Plantations',
                'ordering': ['-date_plantation'],
            },
        ),
        migrations.CreateModel(
            name='Recolte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recolte', models.DateField(verbose_name='Date de récolte')),
                ('quantite_recoltee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité récoltée (kg)')),
                ('qualite', models.CharField(choices=[('EXCELLENTE', 'Excellente'), ('BONNE', 'Bonne'), ('MOYENNE', 'Moyenne')], default='BONNE', max_length=20, verbose_name='Qualité')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('legume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.legume', verbose_name='Légume')),
                ('plantation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recoltes', to='production.plantation', verbose_name='Plantation')),
            ],
            options={
                'verbose_name': 'Récolte',
                'verbose_name_plural': 'Récoltes',
                'ordering': ['-date_recolte'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantité disponible (kg)')),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=10, help_text='Alerte quand le stock descend sous cette valeur', max_digits=10, verbose_name="Seuil d'alerte (kg)")),
                ('date_derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('legume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='production.legume', verbose_name='Légume')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
    ]
