# Generated by Django 5.2.8 on 2025-12-01 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code promo')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('type_reduction', models.CharField(choices=[('POURCENTAGE', 'Pourcentage'), ('MONTANT', 'Montant fixe')], default='POURCENTAGE', max_length=20, verbose_name='Type de réduction')),
                ('valeur', models.DecimalField(decimal_places=2, help_text='Pourcentage (ex: 10 pour 10%) ou montant en FCFA', max_digits=10, verbose_name='Valeur')),
                ('montant_minimum', models.DecimalField(decimal_places=2, default=0, help_text='Montant minimum de commande pour utiliser le code', max_digits=10, verbose_name='Montant minimum')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('nombre_utilisations', models.IntegerField(default=0, verbose_name="Nombre d'utilisations")),
                ('max_utilisations', models.IntegerField(blank=True, help_text='Laisser vide pour illimité', null=True, verbose_name="Maximum d'utilisations")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Code promo',
                'verbose_name_plural': 'Codes promo',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='PointsFidelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Points de fidélité')),
                ('niveau', models.CharField(choices=[('BRONZE', 'Bronze'), ('ARGENT', 'Argent'), ('OR', 'Or'), ('PLATINE', 'Platine')], default='BRONZE', max_length=20, verbose_name='Niveau')),
                ('date_derniere_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_fidelite', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Points de fidélité',
                'verbose_name_plural': 'Points de fidélité',
            },
        ),
        migrations.CreateModel(
            name='HistoriquePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GAIN', 'Gain'), ('DEPENSE', 'Dépense'), ('BONUS', 'Bonus'), ('EXPIRATION', 'Expiration')], max_length=20, verbose_name='Type')),
                ('points', models.IntegerField(verbose_name='Points')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commandes.commande', verbose_name='Commande')),
                ('points_fidelite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='accounts.pointsfidelite', verbose_name='Points de fidélité')),
            ],
            options={
                'verbose_name': 'Historique de points',
                'verbose_name_plural': 'Historique des points',
                'ordering': ['-date'],
            },
        ),
    ]
